---
galaxy_info:
  author: gamersoutreach
  description: Deploy VyOS configuration to devices via SSH
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
